sudo: required
language: generic 
services:
  - docker

before_install:
  - docker build -t marcelorydel/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true marcelorydel/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-851475237407"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY